gpu_list:
    - 0
seed: 1337
dump_path: './outputs/'
defaults:
    - data: hkfd_electron
    - model: resnet152
    - engine: classifier
    - tasks/restore_state: classifier
    - tasks/evaluate: classification
    - _self_
