gpu_list:
    - 0
    - 1
    - 2
    - 3
seed: 1337
dump_path: './outputs/'
defaults:
    - data: hkfd_electron
    - model: resnet152
    - engine: classifier
    - tasks/restore_state: classifier
    - tasks/train: train_resnet
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: classification
    - override loss@tasks.train.loss: cross_entropy
    - override optimizers@tasks.evaluate.optimizers: adamW
    - _self_
model:
  num_output_channels: 4